In [41]:
import pathlib
here = pathlib.Path("..").resolve()
print(here)
main_path = pathlib.Path(".").parent.resolve()
data_path = main_path / "data"
print(f"Data path: {data_path}")

/home/mattiamare/Scrivania/my_project
Data path: /home/mattiamare/Scrivania/my_project/examples/data


In [30]:
import h5py
from my_project.core.spm import load_spm_h5

filepath = "../datasets/400SPM_converted.h5"
data = load_spm_h5(filepath)


In [31]:
print(data.freqs)

[   0.  150.  300.  450.  600.  750.  900. 1050. 1200. 1350. 1500.]


In [ ]:
import numpy as np

with h5py.File(filepath, "r") as f:
    print(f)
    print(list(f.keys()))
    print("\n\n")
    print(frequenze:=f["freqs"])
    haha = np.array(frequenze)
    print(haha)
    print(type(haha))
    print(posizioni:=np.array(f["xyz_pointwise"]))
    

    freqs = np.asarray(haha, dtype=float)
    print(freqs)
    print(type(freqs))


<HDF5 file "400SPM_converted.h5" (mode r)>
['_creator', '_types', 'freqs', 'pointwise', 'recordings', 'validation', 'xyz_pointwise', 'xyz_rec', 'xyz_val']



<HDF5 dataset "freqs": shape (11,), type "<f8">
[   0.  150.  300.  450.  600.  750.  900. 1050. 1200. 1350. 1500.]
<class 'numpy.ndarray'>
[[-3.   -2.25 -0.2 ]
 [-3.   -2.24 -0.2 ]
 [-3.   -2.23 -0.2 ]
 ...
 [-2.   -1.27 -0.2 ]
 [-2.   -1.26 -0.2 ]
 [-2.   -1.25 -0.2 ]]
[   0.  150.  300.  450.  600.  750.  900. 1050. 1200. 1350. 1500.]
<class 'numpy.ndarray'>
