In [41]:
import pathlib
here = pathlib.Path("..").resolve()
print(here)
main_path = pathlib.Path(".").parent.resolve()
data_path = main_path / "data"
print(f"Data path: {data_path}")

/home/mattiamare/Scrivania/my_project
Data path: /home/mattiamare/Scrivania/my_project/examples/data


In [30]:
import h5py
from my_project.core.spm import load_spm_h5

filepath = "../datasets/400SPM_converted.h5"
data = load_spm_h5(filepath)


In [31]:
print(data.freqs)

[   0.  150.  300.  450.  600.  750.  900. 1050. 1200. 1350. 1500.]


In [ ]:
import numpy as np

with h5py.File(filepath, "r") as f:
    print(f)
    print(list(f.keys()))
    print("\n\n")
    print(frequenze:=f["freqs"])
    haha = np.array(frequenze)
    print(haha)
    print(type(haha))
    print(posizioni:=np.array(f["xyz_pointwise"]))
    

    freqs = np.asarray(haha, dtype=float)
    print(freqs)
    print(type(freqs))


<HDF5 file "400SPM_converted.h5" (mode r)>
['_creator', '_types', 'freqs', 'pointwise', 'recordings', 'validation', 'xyz_pointwise', 'xyz_rec', 'xyz_val']



<HDF5 dataset "freqs": shape (11,), type "<f8">
[   0.  150.  300.  450.  600.  750.  900. 1050. 1200. 1350. 1500.]
<class 'numpy.ndarray'>
[[-3.   -2.25 -0.2 ]
 [-3.   -2.24 -0.2 ]
 [-3.   -2.23 -0.2 ]
 ...
 [-2.   -1.27 -0.2 ]
 [-2.   -1.26 -0.2 ]
 [-2.   -1.25 -0.2 ]]
[   0.  150.  300.  450.  600.  750.  900. 1050. 1200. 1350. 1500.]
<class 'numpy.ndarray'>


In [1]:
import math
import torch
from pylebedev import PyLebedev

_cache = {}  # so we don’t recreate PyLebedev() and reload the grid every call

def lebedev_by_order(order: int, *, dtype=torch.float64, device=None):
    """
    Get Lebedev quadrature rule using PyLebedev package.
    Normalizes weights to sum to 4π.
    """
    if order not in _cache:
        lebdev = PyLebedev()
        points, weights = lebdev.get_points_and_weights(order)  # (N,3), (N,)

        # rescale weights to sum to 4π
        weights = weights * (4 * math.pi / weights.sum())

        x, y, z = points.T
        _cache[order] = (x, y, z, weights)

    x, y, z, w = _cache[order]
    return (
        torch.tensor(x, dtype=dtype, device=device),
        torch.tensor(y, dtype=dtype, device=device),
        torch.tensor(z, dtype=dtype, device=device),
        torch.tensor(w, dtype=dtype, device=device),
    )


lebedev_by_order(11)

(tensor([ 1.0000e+00, -1.0000e+00,  6.1232e-17,  6.1232e-17,  0.0000e+00,
          7.4988e-33,  4.3298e-17,  4.3298e-17,  4.3298e-17,  4.3298e-17,
          7.0711e-01,  7.0711e-01, -7.0711e-01, -7.0711e-01,  7.0711e-01,
          7.0711e-01, -7.0711e-01, -7.0711e-01,  5.7735e-01,  5.7735e-01,
          5.7735e-01,  5.7735e-01, -5.7735e-01, -5.7735e-01, -5.7735e-01,
         -5.7735e-01,  3.0151e-01,  3.0151e-01,  3.0151e-01,  3.0151e-01,
         -3.0151e-01, -3.0151e-01, -3.0151e-01, -3.0151e-01,  3.0151e-01,
          3.0151e-01,  3.0151e-01,  3.0151e-01, -3.0151e-01, -3.0151e-01,
         -3.0151e-01, -3.0151e-01,  9.0453e-01, -9.0453e-01,  9.0453e-01,
         -9.0453e-01,  9.0453e-01, -9.0453e-01,  9.0453e-01, -9.0453e-01],
        dtype=torch.float64),
 tensor([ 0.0000e+00,  1.2246e-16,  1.0000e+00, -1.0000e+00,  0.0000e+00,
          1.2246e-16,  7.0711e-01,  7.0711e-01, -7.0711e-01, -7.0711e-01,
          0.0000e+00,  0.0000e+00,  8.6596e-17,  8.6596e-17,  7.0711e-01,
       

In [2]:
len([ 1.0000e+00+0.j, -1.0000e+00+0.j,  6.1232e-17+0.j,  6.1232e-17+0.j,
          0.0000e+00+0.j,  7.4988e-33+0.j,  4.3298e-17+0.j,  4.3298e-17+0.j,
          4.3298e-17+0.j,  4.3298e-17+0.j,  7.0711e-01+0.j,  7.0711e-01+0.j,
         -7.0711e-01+0.j, -7.0711e-01+0.j,  7.0711e-01+0.j,  7.0711e-01+0.j,
         -7.0711e-01+0.j, -7.0711e-01+0.j,  5.7735e-01+0.j,  5.7735e-01+0.j,
          5.7735e-01+0.j,  5.7735e-01+0.j, -5.7735e-01+0.j, -5.7735e-01+0.j,
         -5.7735e-01+0.j, -5.7735e-01+0.j,  3.0151e-01+0.j,  3.0151e-01+0.j,
          3.0151e-01+0.j,  3.0151e-01+0.j, -3.0151e-01+0.j, -3.0151e-01+0.j,
         -3.0151e-01+0.j, -3.0151e-01+0.j,  3.0151e-01+0.j,  3.0151e-01+0.j,
          3.0151e-01+0.j,  3.0151e-01+0.j, -3.0151e-01+0.j, -3.0151e-01+0.j,
         -3.0151e-01+0.j, -3.0151e-01+0.j,  9.0453e-01+0.j, -9.0453e-01+0.j,
          9.0453e-01+0.j, -9.0453e-01+0.j,  9.0453e-01+0.j, -9.0453e-01+0.j,
          9.0453e-01+0.j, -9.0453e-01+0.j])

50